// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: freshcloud.proto

package freshcloud

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type App struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Environment string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Running     bool                   `protobuf:"varint,4,opt,name=running,proto3" json:"running,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *App) Reset() {
	*x = App{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{0}
}

func (x *App) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *App) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *App) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateAppRequest) Reset() {
	*x = CreateAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppRequest) ProtoMessage() {}

func (x *CreateAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppRequest.ProtoReflect.Descriptor instead.
func (*CreateAppRequest) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App *App `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
}

func (x *CreateAppResponse) Reset() {
	*x = CreateAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppResponse) ProtoMessage() {}

func (x *CreateAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppResponse.ProtoReflect.Descriptor instead.
func (*CreateAppResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAppResponse) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

type StopAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StopAppRequest) Reset() {
	*x = StopAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAppRequest) ProtoMessage() {}

func (x *StopAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAppRequest.ProtoReflect.Descriptor instead.
func (*StopAppRequest) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{3}
}

func (x *StopAppRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *StopAppResponse) Reset() {
	*x = StopAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAppResponse) ProtoMessage() {}

func (x *StopAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAppResponse.ProtoReflect.Descriptor instead.
func (*StopAppResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{4}
}

func (x *StopAppResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StopAppResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteAppRequest) Reset() {
	*x = DeleteAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppRequest) ProtoMessage() {}

func (x *DeleteAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppRequest) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAppRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DeleteAppResponse) Reset() {
	*x = DeleteAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppResponse) ProtoMessage() {}

func (x *DeleteAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAppResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteAppResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type LogsAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *LogsAppRequest) Reset() {
	*x = LogsAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogsAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsAppRequest) ProtoMessage() {}

func (x *LogsAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsAppRequest.ProtoReflect.Descriptor instead.
func (*LogsAppRequest) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{7}
}

func (x *LogsAppRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LogsAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Log string `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
}

func (x *LogsAppResponse) Reset() {
	*x = LogsAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogsAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsAppResponse) ProtoMessage() {}

func (x *LogsAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsAppResponse.ProtoReflect.Descriptor instead.
func (*LogsAppResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{8}
}

func (x *LogsAppResponse) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

type ListAppsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apps []*App `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
}

func (x *ListAppsResponse) Reset() {
	*x = ListAppsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsResponse) ProtoMessage() {}

func (x *ListAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsResponse.ProtoReflect.Descriptor instead.
func (*ListAppsResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{9}
}

func (x *ListAppsResponse) GetApps() []*App {
	if x != nil {
		return x.Apps
	}
	return nil
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// Informatio to build the application in the backend
type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commands []string `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{11}
}

func (x *Image) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

type ImageRegistry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url        string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Repository string `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
}

func (x *ImageRegistry) Reset() {
	*x = ImageRegistry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRegistry) ProtoMessage() {}

func (x *ImageRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRegistry.ProtoReflect.Descriptor instead.
func (*ImageRegistry) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{12}
}

func (x *ImageRegistry) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageRegistry) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

type Resources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu    int64 `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory int64 `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Disk   int64 `protobuf:"varint,3,opt,name=disk,proto3" json:"disk,omitempty"`
}

func (x *Resources) Reset() {
	*x = Resources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{13}
}

func (x *Resources) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Resources) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Resources) GetDisk() int64 {
	if x != nil {
		return x.Disk
	}
	return 0
}

type BuildInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image     *Image         `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Registry  *ImageRegistry `protobuf:"bytes,2,opt,name=registry,proto3" json:"registry,omitempty"`
	Resources *Resources     `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
}

func (x *BuildInfo) Reset() {
	*x = BuildInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildInfo) ProtoMessage() {}

func (x *BuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildInfo.ProtoReflect.Descriptor instead.
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{14}
}

func (x *BuildInfo) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *BuildInfo) GetRegistry() *ImageRegistry {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *BuildInfo) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

type DeployAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlobKey string     `protobuf:"bytes,1,opt,name=blobKey,proto3" json:"blobKey,omitempty"`
	Id      string     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name    string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Build   *BuildInfo `protobuf:"bytes,4,opt,name=build,proto3" json:"build,omitempty"`
}

func (x *DeployAppRequest) Reset() {
	*x = DeployAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAppRequest) ProtoMessage() {}

func (x *DeployAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAppRequest.ProtoReflect.Descriptor instead.
func (*DeployAppRequest) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{15}
}

func (x *DeployAppRequest) GetBlobKey() string {
	if x != nil {
		return x.BlobKey
	}
	return ""
}

func (x *DeployAppRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeployAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployAppRequest) GetBuild() *BuildInfo {
	if x != nil {
		return x.Build
	}
	return nil
}

type DeployAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeployAppResponse) Reset() {
	*x = DeployAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAppResponse) ProtoMessage() {}

func (x *DeployAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAppResponse.ProtoReflect.Descriptor instead.
func (*DeployAppResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{16}
}

func (x *DeployAppResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DeployAppResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CronExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName      string            `protobuf:"bytes,1,opt,name=jobName,proto3" json:"jobName,omitempty"`
	Config       map[string]string `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StatusServer uint32            `protobuf:"varint,3,opt,name=statusServer,proto3" json:"statusServer,omitempty"`
}

func (x *CronExecuteRequest) Reset() {
	*x = CronExecuteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CronExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronExecuteRequest) ProtoMessage() {}

func (x *CronExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronExecuteRequest.ProtoReflect.Descriptor instead.
func (*CronExecuteRequest) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{17}
}

func (x *CronExecuteRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *CronExecuteRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CronExecuteRequest) GetStatusServer() uint32 {
	if x != nil {
		return x.StatusServer
	}
	return 0
}

type CronExecuteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output []byte `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CronExecuteResponse) Reset() {
	*x = CronExecuteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CronExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronExecuteResponse) ProtoMessage() {}

func (x *CronExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronExecuteResponse.ProtoReflect.Descriptor instead.
func (*CronExecuteResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{18}
}

func (x *CronExecuteResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *CronExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Dictionary messages
type GetValueDictionaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetValueDictionaryRequest) Reset() {
	*x = GetValueDictionaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetValueDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueDictionaryRequest) ProtoMessage() {}

func (x *GetValueDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueDictionaryRequest.ProtoReflect.Descriptor instead.
func (*GetValueDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{19}
}

func (x *GetValueDictionaryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetValueDictionaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetValueDictionaryResponse) Reset() {
	*x = GetValueDictionaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetValueDictionaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueDictionaryResponse) ProtoMessage() {}

func (x *GetValueDictionaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueDictionaryResponse.ProtoReflect.Descriptor instead.
func (*GetValueDictionaryResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{20}
}

func (x *GetValueDictionaryResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetValueDictionaryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExistsValueDictionaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ExistsValueDictionaryRequest) Reset() {
	*x = ExistsValueDictionaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistsValueDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsValueDictionaryRequest) ProtoMessage() {}

func (x *ExistsValueDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsValueDictionaryRequest.ProtoReflect.Descriptor instead.
func (*ExistsValueDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{21}
}

func (x *ExistsValueDictionaryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ExistsValueDictionaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *ExistsValueDictionaryResponse) Reset() {
	*x = ExistsValueDictionaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistsValueDictionaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsValueDictionaryResponse) ProtoMessage() {}

func (x *ExistsValueDictionaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsValueDictionaryResponse.ProtoReflect.Descriptor instead.
func (*ExistsValueDictionaryResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{22}
}

func (x *ExistsValueDictionaryResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type PutValueDictionaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PutValueDictionaryRequest) Reset() {
	*x = PutValueDictionaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutValueDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutValueDictionaryRequest) ProtoMessage() {}

func (x *PutValueDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutValueDictionaryRequest.ProtoReflect.Descriptor instead.
func (*PutValueDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{23}
}

func (x *PutValueDictionaryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutValueDictionaryRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutValueDictionaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *PutValueDictionaryResponse) Reset() {
	*x = PutValueDictionaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutValueDictionaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutValueDictionaryResponse) ProtoMessage() {}

func (x *PutValueDictionaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutValueDictionaryResponse.ProtoReflect.Descriptor instead.
func (*PutValueDictionaryResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{24}
}

func (x *PutValueDictionaryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteValueDictionaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DeleteValueDictionaryRequest) Reset() {
	*x = DeleteValueDictionaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteValueDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValueDictionaryRequest) ProtoMessage() {}

func (x *DeleteValueDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValueDictionaryRequest.ProtoReflect.Descriptor instead.
func (*DeleteValueDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteValueDictionaryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteValueDictionaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteValueDictionaryResponse) Reset() {
	*x = DeleteValueDictionaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteValueDictionaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValueDictionaryResponse) ProtoMessage() {}

func (x *DeleteValueDictionaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValueDictionaryResponse.ProtoReflect.Descriptor instead.
func (*DeleteValueDictionaryResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteValueDictionaryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PopValueDictionaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *PopValueDictionaryRequest) Reset() {
	*x = PopValueDictionaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopValueDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopValueDictionaryRequest) ProtoMessage() {}

func (x *PopValueDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopValueDictionaryRequest.ProtoReflect.Descriptor instead.
func (*PopValueDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{27}
}

func (x *PopValueDictionaryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type PopValueDictionaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *PopValueDictionaryResponse) Reset() {
	*x = PopValueDictionaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopValueDictionaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopValueDictionaryResponse) ProtoMessage() {}

func (x *PopValueDictionaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopValueDictionaryResponse.ProtoReflect.Descriptor instead.
func (*PopValueDictionaryResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{28}
}

func (x *PopValueDictionaryResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PopValueDictionaryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LengthDictionaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *LengthDictionaryRequest) Reset() {
	*x = LengthDictionaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LengthDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LengthDictionaryRequest) ProtoMessage() {}

func (x *LengthDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LengthDictionaryRequest.ProtoReflect.Descriptor instead.
func (*LengthDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{29}
}

func (x *LengthDictionaryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LengthDictionaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *LengthDictionaryResponse) Reset() {
	*x = LengthDictionaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LengthDictionaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LengthDictionaryResponse) ProtoMessage() {}

func (x *LengthDictionaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LengthDictionaryResponse.ProtoReflect.Descriptor instead.
func (*LengthDictionaryResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{30}
}

func (x *LengthDictionaryResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *LengthDictionaryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Queue messages
type ProduceValueQueueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic   string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Message []byte `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ProduceValueQueueRequest) Reset() {
	*x = ProduceValueQueueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProduceValueQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceValueQueueRequest) ProtoMessage() {}

func (x *ProduceValueQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceValueQueueRequest.ProtoReflect.Descriptor instead.
func (*ProduceValueQueueRequest) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{31}
}

func (x *ProduceValueQueueRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProduceValueQueueRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type ProduceValueQueueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack   bool   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ProduceValueQueueResponse) Reset() {
	*x = ProduceValueQueueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProduceValueQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceValueQueueResponse) ProtoMessage() {}

func (x *ProduceValueQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceValueQueueResponse.ProtoReflect.Descriptor instead.
func (*ProduceValueQueueResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{32}
}

func (x *ProduceValueQueueResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *ProduceValueQueueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConsumeValuesQueueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *ConsumeValuesQueueRequest) Reset() {
	*x = ConsumeValuesQueueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumeValuesQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeValuesQueueRequest) ProtoMessage() {}

func (x *ConsumeValuesQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeValuesQueueRequest.ProtoReflect.Descriptor instead.
func (*ConsumeValuesQueueRequest) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{33}
}

func (x *ConsumeValuesQueueRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type ConsumeValuesQueueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ConsumeValuesQueueResponse) Reset() {
	*x = ConsumeValuesQueueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumeValuesQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeValuesQueueResponse) ProtoMessage() {}

func (x *ConsumeValuesQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeValuesQueueResponse.ProtoReflect.Descriptor instead.
func (*ConsumeValuesQueueResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{34}
}

func (x *ConsumeValuesQueueResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

// SecretHandler messages
type LoadSecretsFromAPIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationId string `protobuf:"bytes,1,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
}

func (x *LoadSecretsFromAPIRequest) Reset() {
	*x = LoadSecretsFromAPIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadSecretsFromAPIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSecretsFromAPIRequest) ProtoMessage() {}

func (x *LoadSecretsFromAPIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSecretsFromAPIRequest.ProtoReflect.Descriptor instead.
func (*LoadSecretsFromAPIRequest) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{35}
}

func (x *LoadSecretsFromAPIRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type LoadSecretsFromAPIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values map[string]string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *LoadSecretsFromAPIResponse) Reset() {
	*x = LoadSecretsFromAPIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freshcloud_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadSecretsFromAPIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSecretsFromAPIResponse) ProtoMessage() {}

func (x *LoadSecretsFromAPIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freshcloud_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSecretsFromAPIResponse.ProtoReflect.Descriptor instead.
func (*LoadSecretsFromAPIResponse) Descriptor() ([]byte, []int) {
	return file_freshcloud_proto_rawDescGZIP(), []int{36}
}

func (x *LoadSecretsFromAPIResponse) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_freshcloud_proto protoreflect.FileDescriptor

var file_freshcloud_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x01, 0x0a, 0x03, 0x41,
	0x70, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6e, 0x76,
	0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x26, 0x0a, 0x10,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x61, 0x70, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x41, 0x70, 0x70, 0x52, 0x03, 0x61, 0x70, 0x70, 0x22, 0x20, 0x0a, 0x0e,
	0x53, 0x74, 0x6f, 0x70, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x33,
	0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x22, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x20,
	0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x73, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x23, 0x0a, 0x0f, 0x4c, 0x6f, 0x67, 0x73, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6c, 0x6f, 0x67, 0x22, 0x37, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x70, 0x70,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x61, 0x70, 0x70,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x41, 0x70, 0x70, 0x52, 0x04, 0x61, 0x70, 0x70, 0x73, 0x22, 0x20,
	0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x23, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x73, 0x22, 0x41, 0x0a, 0x0d, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x49, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64,
	0x69, 0x73, 0x6b, 0x22, 0xa0, 0x01, 0x0a, 0x09, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x27, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x79, 0x12, 0x33, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x09, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x7d, 0x0a, 0x10, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c,
	0x6f, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6c, 0x6f,
	0x62, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x22, 0x3d, 0x0a, 0x11, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x41,
	0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0xd1, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x6f, 0x6e, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6a,
	0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f,
	0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x42, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2e, 0x43, 0x72, 0x6f, 0x6e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0c, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x39, 0x0a,
	0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x43, 0x0a, 0x13, 0x43, 0x72, 0x6f, 0x6e,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2d, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x48, 0x0a, 0x1a,
	0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x30, 0x0a, 0x1c, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x37, 0x0a, 0x1d, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69,
	0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74,
	0x73, 0x22, 0x43, 0x0a, 0x19, 0x50, 0x75, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x32, 0x0a, 0x1a, 0x50, 0x75, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x30, 0x0a, 0x1c, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x35, 0x0a, 0x1d,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x2d, 0x0a, 0x19, 0x50, 0x6f, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0x48, 0x0a, 0x1a, 0x50, 0x6f, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2b, 0x0a, 0x17,
	0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x46, 0x0a, 0x18, 0x4c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x4a, 0x0a, 0x18, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x43, 0x0a,
	0x19, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x31, 0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x36, 0x0a, 0x1a, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x41, 0x0a,
	0x19, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x46, 0x72, 0x6f, 0x6d,
	0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x22, 0xa3, 0x01, 0x0a, 0x1a, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73,
	0x46, 0x72, 0x6f, 0x6d, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4a, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x32, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4c, 0x6f, 0x61,
	0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x50, 0x49, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x9a, 0x0b, 0x0a, 0x0a, 0x46, 0x72, 0x65, 0x73, 0x68,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x12, 0x48, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x70, 0x70, 0x12, 0x1c, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x42, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x70, 0x70, 0x12, 0x1a, 0x2e, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x70, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70,
	0x12, 0x1c, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a,
	0x07, 0x4c, 0x6f, 0x67, 0x73, 0x41, 0x70, 0x70, 0x12, 0x1a, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4c, 0x6f, 0x67, 0x73, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x4c, 0x6f, 0x67, 0x73, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x30, 0x01, 0x12, 0x40, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x70, 0x70, 0x73, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1c, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x70, 0x70, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x41,
	0x70, 0x70, 0x12, 0x1c, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x63, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x25, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6c, 0x0a, 0x15, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x28, 0x2e,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x63, 0x0a, 0x12, 0x50, 0x75, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x25, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x50, 0x75, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x26, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x50, 0x75, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6c, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79,
	0x12, 0x28, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x12, 0x50, 0x6f, 0x70, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x25, 0x2e, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x50, 0x6f, 0x70, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x50, 0x6f, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x10, 0x4c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x23,
	0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2e, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x11, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x24,
	0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x12, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x12, 0x25, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x30, 0x01, 0x12, 0x63, 0x0a, 0x12, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x73, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x50, 0x49, 0x12, 0x25, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x73, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x26, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4c, 0x6f, 0x61,
	0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x50, 0x49, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x18, 0x2e, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x10, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x3a, 0x01, 0x2a, 0x22, 0x05, 0x2f, 0x70,
	0x69, 0x6e, 0x67, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x69, 0x6f, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x66, 0x72, 0x65, 0x73, 0x68, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_freshcloud_proto_rawDescOnce sync.Once
	file_freshcloud_proto_rawDescData = file_freshcloud_proto_rawDesc
)

func file_freshcloud_proto_rawDescGZIP() []byte {
	file_freshcloud_proto_rawDescOnce.Do(func() {
		file_freshcloud_proto_rawDescData = protoimpl.X.CompressGZIP(file_freshcloud_proto_rawDescData)
	})
	return file_freshcloud_proto_rawDescData
}

var file_freshcloud_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_freshcloud_proto_goTypes = []interface{}{
	(*App)(nil),                           // 0: freshcloud.App
	(*CreateAppRequest)(nil),              // 1: freshcloud.CreateAppRequest
	(*CreateAppResponse)(nil),             // 2: freshcloud.CreateAppResponse
	(*StopAppRequest)(nil),                // 3: freshcloud.StopAppRequest
	(*StopAppResponse)(nil),               // 4: freshcloud.StopAppResponse
	(*DeleteAppRequest)(nil),              // 5: freshcloud.DeleteAppRequest
	(*DeleteAppResponse)(nil),             // 6: freshcloud.DeleteAppResponse
	(*LogsAppRequest)(nil),                // 7: freshcloud.LogsAppRequest
	(*LogsAppResponse)(nil),               // 8: freshcloud.LogsAppResponse
	(*ListAppsResponse)(nil),              // 9: freshcloud.ListAppsResponse
	(*PingResponse)(nil),                  // 10: freshcloud.PingResponse
	(*Image)(nil),                         // 11: freshcloud.Image
	(*ImageRegistry)(nil),                 // 12: freshcloud.ImageRegistry
	(*Resources)(nil),                     // 13: freshcloud.Resources
	(*BuildInfo)(nil),                     // 14: freshcloud.BuildInfo
	(*DeployAppRequest)(nil),              // 15: freshcloud.DeployAppRequest
	(*DeployAppResponse)(nil),             // 16: freshcloud.DeployAppResponse
	(*CronExecuteRequest)(nil),            // 17: freshcloud.CronExecuteRequest
	(*CronExecuteResponse)(nil),           // 18: freshcloud.CronExecuteResponse
	(*GetValueDictionaryRequest)(nil),     // 19: freshcloud.GetValueDictionaryRequest
	(*GetValueDictionaryResponse)(nil),    // 20: freshcloud.GetValueDictionaryResponse
	(*ExistsValueDictionaryRequest)(nil),  // 21: freshcloud.ExistsValueDictionaryRequest
	(*ExistsValueDictionaryResponse)(nil), // 22: freshcloud.ExistsValueDictionaryResponse
	(*PutValueDictionaryRequest)(nil),     // 23: freshcloud.PutValueDictionaryRequest
	(*PutValueDictionaryResponse)(nil),    // 24: freshcloud.PutValueDictionaryResponse
	(*DeleteValueDictionaryRequest)(nil),  // 25: freshcloud.DeleteValueDictionaryRequest
	(*DeleteValueDictionaryResponse)(nil), // 26: freshcloud.DeleteValueDictionaryResponse
	(*PopValueDictionaryRequest)(nil),     // 27: freshcloud.PopValueDictionaryRequest
	(*PopValueDictionaryResponse)(nil),    // 28: freshcloud.PopValueDictionaryResponse
	(*LengthDictionaryRequest)(nil),       // 29: freshcloud.LengthDictionaryRequest
	(*LengthDictionaryResponse)(nil),      // 30: freshcloud.LengthDictionaryResponse
	(*ProduceValueQueueRequest)(nil),      // 31: freshcloud.ProduceValueQueueRequest
	(*ProduceValueQueueResponse)(nil),     // 32: freshcloud.ProduceValueQueueResponse
	(*ConsumeValuesQueueRequest)(nil),     // 33: freshcloud.ConsumeValuesQueueRequest
	(*ConsumeValuesQueueResponse)(nil),    // 34: freshcloud.ConsumeValuesQueueResponse
	(*LoadSecretsFromAPIRequest)(nil),     // 35: freshcloud.LoadSecretsFromAPIRequest
	(*LoadSecretsFromAPIResponse)(nil),    // 36: freshcloud.LoadSecretsFromAPIResponse
	nil,                                   // 37: freshcloud.CronExecuteRequest.ConfigEntry
	nil,                                   // 38: freshcloud.LoadSecretsFromAPIResponse.ValuesEntry
	(*timestamppb.Timestamp)(nil),         // 39: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 40: google.protobuf.Empty
}
var file_freshcloud_proto_depIdxs = []int32{
	39, // 0: freshcloud.App.createdAt:type_name -> google.protobuf.Timestamp
	0,  // 1: freshcloud.CreateAppResponse.app:type_name -> freshcloud.App
	0,  // 2: freshcloud.ListAppsResponse.apps:type_name -> freshcloud.App
	11, // 3: freshcloud.BuildInfo.image:type_name -> freshcloud.Image
	12, // 4: freshcloud.BuildInfo.registry:type_name -> freshcloud.ImageRegistry
	13, // 5: freshcloud.BuildInfo.resources:type_name -> freshcloud.Resources
	14, // 6: freshcloud.DeployAppRequest.build:type_name -> freshcloud.BuildInfo
	37, // 7: freshcloud.CronExecuteRequest.config:type_name -> freshcloud.CronExecuteRequest.ConfigEntry
	38, // 8: freshcloud.LoadSecretsFromAPIResponse.values:type_name -> freshcloud.LoadSecretsFromAPIResponse.ValuesEntry
	1,  // 9: freshcloud.Freshcloud.CreateApp:input_type -> freshcloud.CreateAppRequest
	3,  // 10: freshcloud.Freshcloud.StopApp:input_type -> freshcloud.StopAppRequest
	5,  // 11: freshcloud.Freshcloud.DeleteApp:input_type -> freshcloud.DeleteAppRequest
	7,  // 12: freshcloud.Freshcloud.LogsApp:input_type -> freshcloud.LogsAppRequest
	40, // 13: freshcloud.Freshcloud.ListApps:input_type -> google.protobuf.Empty
	15, // 14: freshcloud.Freshcloud.DeployApp:input_type -> freshcloud.DeployAppRequest
	19, // 15: freshcloud.Freshcloud.GetValueDictionary:input_type -> freshcloud.GetValueDictionaryRequest
	21, // 16: freshcloud.Freshcloud.ExistsValueDictionary:input_type -> freshcloud.ExistsValueDictionaryRequest
	23, // 17: freshcloud.Freshcloud.PutValueDictionary:input_type -> freshcloud.PutValueDictionaryRequest
	25, // 18: freshcloud.Freshcloud.DeleteValueDictionary:input_type -> freshcloud.DeleteValueDictionaryRequest
	27, // 19: freshcloud.Freshcloud.PopValueDictionary:input_type -> freshcloud.PopValueDictionaryRequest
	29, // 20: freshcloud.Freshcloud.LengthDictionary:input_type -> freshcloud.LengthDictionaryRequest
	31, // 21: freshcloud.Freshcloud.ProduceValueQueue:input_type -> freshcloud.ProduceValueQueueRequest
	33, // 22: freshcloud.Freshcloud.ConsumeValuesQueue:input_type -> freshcloud.ConsumeValuesQueueRequest
	35, // 23: freshcloud.Freshcloud.LoadSecretsFromAPI:input_type -> freshcloud.LoadSecretsFromAPIRequest
	40, // 24: freshcloud.Freshcloud.Ping:input_type -> google.protobuf.Empty
	2,  // 25: freshcloud.Freshcloud.CreateApp:output_type -> freshcloud.CreateAppResponse
	4,  // 26: freshcloud.Freshcloud.StopApp:output_type -> freshcloud.StopAppResponse
	6,  // 27: freshcloud.Freshcloud.DeleteApp:output_type -> freshcloud.DeleteAppResponse
	8,  // 28: freshcloud.Freshcloud.LogsApp:output_type -> freshcloud.LogsAppResponse
	9,  // 29: freshcloud.Freshcloud.ListApps:output_type -> freshcloud.ListAppsResponse
	16, // 30: freshcloud.Freshcloud.DeployApp:output_type -> freshcloud.DeployAppResponse
	20, // 31: freshcloud.Freshcloud.GetValueDictionary:output_type -> freshcloud.GetValueDictionaryResponse
	22, // 32: freshcloud.Freshcloud.ExistsValueDictionary:output_type -> freshcloud.ExistsValueDictionaryResponse
	24, // 33: freshcloud.Freshcloud.PutValueDictionary:output_type -> freshcloud.PutValueDictionaryResponse
	26, // 34: freshcloud.Freshcloud.DeleteValueDictionary:output_type -> freshcloud.DeleteValueDictionaryResponse
	28, // 35: freshcloud.Freshcloud.PopValueDictionary:output_type -> freshcloud.PopValueDictionaryResponse
	30, // 36: freshcloud.Freshcloud.LengthDictionary:output_type -> freshcloud.LengthDictionaryResponse
	32, // 37: freshcloud.Freshcloud.ProduceValueQueue:output_type -> freshcloud.ProduceValueQueueResponse
	34, // 38: freshcloud.Freshcloud.ConsumeValuesQueue:output_type -> freshcloud.ConsumeValuesQueueResponse
	36, // 39: freshcloud.Freshcloud.LoadSecretsFromAPI:output_type -> freshcloud.LoadSecretsFromAPIResponse
	10, // 40: freshcloud.Freshcloud.Ping:output_type -> freshcloud.PingResponse
	25, // [25:41] is the sub-list for method output_type
	9,  // [9:25] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_freshcloud_proto_init() }
func file_freshcloud_proto_init() {
	if File_freshcloud_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_freshcloud_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogsAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogsAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAppsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageRegistry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CronExecuteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CronExecuteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetValueDictionaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetValueDictionaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistsValueDictionaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistsValueDictionaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutValueDictionaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutValueDictionaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteValueDictionaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteValueDictionaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopValueDictionaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopValueDictionaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LengthDictionaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LengthDictionaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProduceValueQueueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProduceValueQueueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumeValuesQueueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumeValuesQueueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadSecretsFromAPIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freshcloud_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadSecretsFromAPIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_freshcloud_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_freshcloud_proto_goTypes,
		DependencyIndexes: file_freshcloud_proto_depIdxs,
		MessageInfos:      file_freshcloud_proto_msgTypes,
	}.Build()
	File_freshcloud_proto = out.File
	file_freshcloud_proto_rawDesc = nil
	file_freshcloud_proto_goTypes = nil
	file_freshcloud_proto_depIdxs = nil
}
